package io.github.stream29.proxy.relocate.com.aallam.openai.api.chat

import io.github.stream29.proxy.relocate.com.aallam.openai.api.core.FinishReason
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
@Serializable
data class ChatChunk(
    /**
     * Chat choice index.
     */
    @SerialName("index") val index: Int,
    /**
     * The generated chat message.
     */
    @SerialName("delta") val delta: ChatDelta? = null,

    /**
     * Azure content filter offsets
     */
    @SerialName("content_filter_offsets") val contentFilterOffsets: ContentFilterOffsets? = null,

    /**
     * Azure content filter results
     */
    @SerialName("content_filter_results") val contentFilterResults: ContentFilterResults? = null,

    /**
     * The reason why OpenAI stopped generating.
     */
    @SerialName("finish_reason") val finishReason: FinishReason? = null,
)
