package io.github.stream29.proxy.relocate.com.aallam.openai.api.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a function invocation with its name and serialized arguments as generated by the model.
 *
 * In scenarios such as a streaming variant of the chat API, both [nameOrNull] and [argumentsOrNull] can be null.
 */
@Serializable
data class FunctionCall(
    /**
     * The name of the function to call.
     */
    @SerialName("name") val nameOrNull: String? = null,

    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     * Note that the model does not always generate valid JSON, and may hallucinate parameters
     * not defined by your function schema.
     * Validate the arguments in your code before calling your function.
     */
    @SerialName("arguments") val argumentsOrNull: String? = null,
) {

    /**
     * The name of the function to call.
     */
    val name: String
        get() = requireNotNull(nameOrNull)

}
